apiVersion: v1
kind: Service
metadata:
    name: "dsk7-f4bc"
    labels:
        app: "dsk7-f4bc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dsk7-f4bc"